#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using Abeced.Data;

namespace Abeced.Data
{
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.Diagnostics.DebuggerDisplay("IndCardId: {IndCardId}")]
    public partial class AllCard : EntityBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="AllCard"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static AllCard()
        {
            AddSharedRules();
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="AllCard"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public AllCard()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        protected override void Initialize()
        {
            OnCreated();
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _indCardId;
        
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String IndCardId
        {
            get { return _indCardId; }
            set
            {
                OnIndCardIdChanging(value, _indCardId);
                SendPropertyChanging("IndCardId");
                _indCardId = value;
                SendPropertyChanged("IndCardId");
                OnIndCardIdChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _csessionId;
        
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String CsessionId
        {
            get { return _csessionId; }
            set
            {
                OnCsessionIdChanging(value, _csessionId);
                SendPropertyChanging("CsessionId");
                _csessionId = value;
                SendPropertyChanged("CsessionId");
                OnCsessionIdChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _flashcardId;
        
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String FlashcardId
        {
            get { return _flashcardId; }
            set
            {
                OnFlashcardIdChanging(value, _flashcardId);
                SendPropertyChanging("FlashcardId");
                _flashcardId = value;
                SendPropertyChanged("FlashcardId");
                OnFlashcardIdChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Boolean _correctAnswer;
        
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Boolean CorrectAnswer
        {
            get { return _correctAnswer; }
            set
            {
                OnCorrectAnswerChanging(value, _correctAnswer);
                SendPropertyChanging("CorrectAnswer");
                _correctAnswer = value;
                SendPropertyChanged("CorrectAnswer");
                OnCorrectAnswerChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Double? _elapseTime;
        
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Double? ElapseTime
        {
            get { return _elapseTime; }
            set
            {
                OnElapseTimeChanging(value, _elapseTime);
                SendPropertyChanging("ElapseTime");
                _elapseTime = value;
                SendPropertyChanged("ElapseTime");
                OnElapseTimeChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _revisionOrder;
        
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String RevisionOrder
        {
            get { return _revisionOrder; }
            set
            {
                OnRevisionOrderChanging(value, _revisionOrder);
                SendPropertyChanging("RevisionOrder");
                _revisionOrder = value;
                SendPropertyChanged("RevisionOrder");
                OnRevisionOrderChanged(value);
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        #endregion
        
        #region Extensibility Method
        
        static partial void AddSharedRules();
        
        partial void OnCreated();
        
        partial void OnIndCardIdChanging(System.String newValue, System.String oldValue);
        
        partial void OnIndCardIdChanged(System.String value);
        
        partial void OnCsessionIdChanging(System.String newValue, System.String oldValue);
        
        partial void OnCsessionIdChanged(System.String value);
        
        partial void OnFlashcardIdChanging(System.String newValue, System.String oldValue);
        
        partial void OnFlashcardIdChanged(System.String value);
        
        partial void OnCorrectAnswerChanging(System.Boolean newValue, System.Boolean oldValue);
        
        partial void OnCorrectAnswerChanged(System.Boolean value);
        
        partial void OnElapseTimeChanging(System.Double? newValue, System.Double? oldValue);
        
        partial void OnElapseTimeChanged(System.Double? value);
        
        partial void OnRevisionOrderChanging(System.String newValue, System.String oldValue);
        
        partial void OnRevisionOrderChanged(System.String value);
        
        
        #endregion
        
        #region Clone
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual AllCard Clone()
        {
            return (AllCard)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="AllCard"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="AllCard"/> instance.</param>
        /// <returns>An instance of <see cref="AllCard"/> that is deserialized from the XML String.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static AllCard FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AllCard));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as AllCard;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="AllCard"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="AllCard"/> instance.</param>
        /// <returns>An instance of <see cref="AllCard"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static AllCard FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AllCard));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as AllCard;
            }
        }
        
        #endregion
    }
}

#pragma warning restore 1591
#pragma warning restore 0414
