#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using Abeced.Data;

namespace Abeced.Data
{
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.Diagnostics.DebuggerDisplay("Inviteid: {Inviteid}")]
    public partial class Invitation : EntityBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="Invitation"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static Invitation()
        {
            AddSharedRules();
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Invitation"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public Invitation()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        protected override void Initialize()
        {
            OnCreated();
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _inviteid;
        
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String Inviteid
        {
            get { return _inviteid; }
            set
            {
                OnInviteidChanging(value, _inviteid);
                SendPropertyChanging("Inviteid");
                _inviteid = value;
                SendPropertyChanged("Inviteid");
                OnInviteidChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _userid;
        
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String Userid
        {
            get { return _userid; }
            set
            {
                OnUseridChanging(value, _userid);
                SendPropertyChanging("Userid");
                _userid = value;
                SendPropertyChanged("Userid");
                OnUseridChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _email;
        
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String Email
        {
            get { return _email; }
            set
            {
                OnEmailChanging(value, _email);
                SendPropertyChanging("Email");
                _email = value;
                SendPropertyChanged("Email");
                OnEmailChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.DateTime? _inviteDate;
        
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.DateTime? InviteDate
        {
            get { return _inviteDate; }
            set
            {
                OnInviteDateChanging(value, _inviteDate);
                SendPropertyChanging("InviteDate");
                _inviteDate = value;
                SendPropertyChanged("InviteDate");
                OnInviteDateChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Boolean? _inviteAccept;
        
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Boolean? InviteAccept
        {
            get { return _inviteAccept; }
            set
            {
                OnInviteAcceptChanging(value, _inviteAccept);
                SendPropertyChanging("InviteAccept");
                _inviteAccept = value;
                SendPropertyChanged("InviteAccept");
                OnInviteAcceptChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.DateTime? _acceptedDate;
        
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.DateTime? AcceptedDate
        {
            get { return _acceptedDate; }
            set
            {
                OnAcceptedDateChanging(value, _acceptedDate);
                SendPropertyChanging("AcceptedDate");
                _acceptedDate = value;
                SendPropertyChanged("AcceptedDate");
                OnAcceptedDateChanged(value);
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        #endregion
        
        #region Extensibility Method
        
        static partial void AddSharedRules();
        
        partial void OnCreated();
        
        partial void OnInviteidChanging(System.String newValue, System.String oldValue);
        
        partial void OnInviteidChanged(System.String value);
        
        partial void OnUseridChanging(System.String newValue, System.String oldValue);
        
        partial void OnUseridChanged(System.String value);
        
        partial void OnEmailChanging(System.String newValue, System.String oldValue);
        
        partial void OnEmailChanged(System.String value);
        
        partial void OnInviteDateChanging(System.DateTime? newValue, System.DateTime? oldValue);
        
        partial void OnInviteDateChanged(System.DateTime? value);
        
        partial void OnInviteAcceptChanging(System.Boolean? newValue, System.Boolean? oldValue);
        
        partial void OnInviteAcceptChanged(System.Boolean? value);
        
        partial void OnAcceptedDateChanging(System.DateTime? newValue, System.DateTime? oldValue);
        
        partial void OnAcceptedDateChanged(System.DateTime? value);
        
        
        #endregion
        
        #region Clone
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual Invitation Clone()
        {
            return (Invitation)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="Invitation"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Invitation"/> instance.</param>
        /// <returns>An instance of <see cref="Invitation"/> that is deserialized from the XML String.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static Invitation FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(Invitation));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as Invitation;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Invitation"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Invitation"/> instance.</param>
        /// <returns>An instance of <see cref="Invitation"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static Invitation FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(Invitation));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as Invitation;
            }
        }
        
        #endregion
    }
}

#pragma warning restore 1591
#pragma warning restore 0414
