#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using Abeced.Data;

namespace Abeced.Data
{
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.Diagnostics.DebuggerDisplay("Catid: {Catid}")]
    public partial class LookupCategory : EntityBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="LookupCategory"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static LookupCategory()
        {
            AddSharedRules();
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="LookupCategory"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public LookupCategory()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        protected override void Initialize()
        {
            OnCreated();
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _catid;
        
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String Catid
        {
            get { return _catid; }
            set
            {
                OnCatidChanging(value, _catid);
                SendPropertyChanging("Catid");
                _catid = value;
                SendPropertyChanged("Catid");
                OnCatidChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _catTitle;
        
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String CatTitle
        {
            get { return _catTitle; }
            set
            {
                OnCatTitleChanging(value, _catTitle);
                SendPropertyChanging("CatTitle");
                _catTitle = value;
                SendPropertyChanged("CatTitle");
                OnCatTitleChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _subCatid;
        
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String SubCatid
        {
            get { return _subCatid; }
            set
            {
                OnSubCatidChanging(value, _subCatid);
                SendPropertyChanging("SubCatid");
                _subCatid = value;
                SendPropertyChanged("SubCatid");
                OnSubCatidChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.DateTime? _lastupdate;
        
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.DateTime? Lastupdate
        {
            get { return _lastupdate; }
            set
            {
                OnLastupdateChanging(value, _lastupdate);
                SendPropertyChanging("Lastupdate");
                _lastupdate = value;
                SendPropertyChanged("Lastupdate");
                OnLastupdateChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _catImg;
        
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String CatImg
        {
            get { return _catImg; }
            set
            {
                OnCatImgChanging(value, _catImg);
                SendPropertyChanging("CatImg");
                _catImg = value;
                SendPropertyChanged("CatImg");
                OnCatImgChanged(value);
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private IList<LookupSubcategory> _lookupSubcategoryList;
        
        [System.Runtime.Serialization.DataMember(Order = 6, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual IList<LookupSubcategory> LookupSubcategoryList
        {
            get { return _lookupSubcategoryList; }
            set
            {
                OnLookupSubcategoryListChanging(value, _lookupSubcategoryList);
                SendPropertyChanging("LookupSubcategoryList");
                _lookupSubcategoryList = value;
                SendPropertyChanged("LookupSubcategoryList");
                OnLookupSubcategoryListChanged(value);
            }
        }
        
        #endregion
        
        #region Extensibility Method
        
        static partial void AddSharedRules();
        
        partial void OnCreated();
        
        partial void OnCatidChanging(System.String newValue, System.String oldValue);
        
        partial void OnCatidChanged(System.String value);
        
        partial void OnCatTitleChanging(System.String newValue, System.String oldValue);
        
        partial void OnCatTitleChanged(System.String value);
        
        partial void OnSubCatidChanging(System.String newValue, System.String oldValue);
        
        partial void OnSubCatidChanged(System.String value);
        
        partial void OnLastupdateChanging(System.DateTime? newValue, System.DateTime? oldValue);
        
        partial void OnLastupdateChanged(System.DateTime? value);
        
        partial void OnCatImgChanging(System.String newValue, System.String oldValue);
        
        partial void OnCatImgChanged(System.String value);
        
        
        partial void OnLookupSubcategoryListChanging(IList<LookupSubcategory> newValue, IList<LookupSubcategory> oldValue);
        
        partial void OnLookupSubcategoryListChanged(IList<LookupSubcategory> value);
        
        #endregion
        
        #region Clone
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual LookupCategory Clone()
        {
            return (LookupCategory)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="LookupCategory"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="LookupCategory"/> instance.</param>
        /// <returns>An instance of <see cref="LookupCategory"/> that is deserialized from the XML String.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static LookupCategory FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(LookupCategory));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as LookupCategory;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="LookupCategory"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="LookupCategory"/> instance.</param>
        /// <returns>An instance of <see cref="LookupCategory"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static LookupCategory FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(LookupCategory));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as LookupCategory;
            }
        }
        
        #endregion
    }
}

#pragma warning restore 1591
#pragma warning restore 0414
