#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using Abeced.Data;

namespace Abeced.Data
{
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.Diagnostics.DebuggerDisplay("Agroupid: {Agroupid}")]
    public partial class LookupAgegroup : EntityBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="LookupAgegroup"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static LookupAgegroup()
        {
            AddSharedRules();
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="LookupAgegroup"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public LookupAgegroup()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        protected override void Initialize()
        {
            OnCreated();
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Int32 _agroupid;
        
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Int32 Agroupid
        {
            get { return _agroupid; }
            set
            {
                OnAgroupidChanging(value, _agroupid);
                SendPropertyChanging("Agroupid");
                _agroupid = value;
                SendPropertyChanged("Agroupid");
                OnAgroupidChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _agegroup;
        
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String Agegroup
        {
            get { return _agegroup; }
            set
            {
                OnAgegroupChanging(value, _agegroup);
                SendPropertyChanging("Agegroup");
                _agegroup = value;
                SendPropertyChanged("Agegroup");
                OnAgegroupChanged(value);
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        #endregion
        
        #region Extensibility Method
        
        static partial void AddSharedRules();
        
        partial void OnCreated();
        
        partial void OnAgroupidChanging(System.Int32 newValue, System.Int32 oldValue);
        
        partial void OnAgroupidChanged(System.Int32 value);
        
        partial void OnAgegroupChanging(System.String newValue, System.String oldValue);
        
        partial void OnAgegroupChanged(System.String value);
        
        
        #endregion
        
        #region Clone
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual LookupAgegroup Clone()
        {
            return (LookupAgegroup)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="LookupAgegroup"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="LookupAgegroup"/> instance.</param>
        /// <returns>An instance of <see cref="LookupAgegroup"/> that is deserialized from the XML String.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static LookupAgegroup FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(LookupAgegroup));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as LookupAgegroup;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="LookupAgegroup"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="LookupAgegroup"/> instance.</param>
        /// <returns>An instance of <see cref="LookupAgegroup"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static LookupAgegroup FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(LookupAgegroup));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as LookupAgegroup;
            }
        }
        
        #endregion
    }
}

#pragma warning restore 1591
#pragma warning restore 0414
