#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using Abeced.Data;

namespace Abeced.Data
{
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.Diagnostics.DebuggerDisplay("Identification: {Identification}")]
    public partial class Messageofday : EntityBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="Messageofday"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static Messageofday()
        {
            AddSharedRules();
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Messageofday"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public Messageofday()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        protected override void Initialize()
        {
            OnCreated();
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _identification;
        
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String Identification
        {
            get { return _identification; }
            set
            {
                OnIdentificationChanging(value, _identification);
                SendPropertyChanging("Identification");
                _identification = value;
                SendPropertyChanged("Identification");
                OnIdentificationChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.DateTime _msgdate;
        
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.DateTime Msgdate
        {
            get { return _msgdate; }
            set
            {
                OnMsgdateChanging(value, _msgdate);
                SendPropertyChanging("Msgdate");
                _msgdate = value;
                SendPropertyChanged("Msgdate");
                OnMsgdateChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _msgtext;
        
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String Msgtext
        {
            get { return _msgtext; }
            set
            {
                OnMsgtextChanging(value, _msgtext);
                SendPropertyChanging("Msgtext");
                _msgtext = value;
                SendPropertyChanged("Msgtext");
                OnMsgtextChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _entryby;
        
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String Entryby
        {
            get { return _entryby; }
            set
            {
                OnEntrybyChanging(value, _entryby);
                SendPropertyChanging("Entryby");
                _entryby = value;
                SendPropertyChanged("Entryby");
                OnEntrybyChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.DateTime _entrydate;
        
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.DateTime Entrydate
        {
            get { return _entrydate; }
            set
            {
                OnEntrydateChanging(value, _entrydate);
                SendPropertyChanging("Entrydate");
                _entrydate = value;
                SendPropertyChanged("Entrydate");
                OnEntrydateChanged(value);
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        #endregion
        
        #region Extensibility Method
        
        static partial void AddSharedRules();
        
        partial void OnCreated();
        
        partial void OnIdentificationChanging(System.String newValue, System.String oldValue);
        
        partial void OnIdentificationChanged(System.String value);
        
        partial void OnMsgdateChanging(System.DateTime newValue, System.DateTime oldValue);
        
        partial void OnMsgdateChanged(System.DateTime value);
        
        partial void OnMsgtextChanging(System.String newValue, System.String oldValue);
        
        partial void OnMsgtextChanged(System.String value);
        
        partial void OnEntrybyChanging(System.String newValue, System.String oldValue);
        
        partial void OnEntrybyChanged(System.String value);
        
        partial void OnEntrydateChanging(System.DateTime newValue, System.DateTime oldValue);
        
        partial void OnEntrydateChanged(System.DateTime value);
        
        
        #endregion
        
        #region Clone
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual Messageofday Clone()
        {
            return (Messageofday)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="Messageofday"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Messageofday"/> instance.</param>
        /// <returns>An instance of <see cref="Messageofday"/> that is deserialized from the XML String.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static Messageofday FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(Messageofday));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as Messageofday;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Messageofday"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Messageofday"/> instance.</param>
        /// <returns>An instance of <see cref="Messageofday"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static Messageofday FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(Messageofday));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as Messageofday;
            }
        }
        
        #endregion
    }
}

#pragma warning restore 1591
#pragma warning restore 0414
