#pragma warning disable 1591
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Text;
using NHibernate;
using NHibernate.Cfg;
using CodeSmith.Data.Linq;
using CodeSmith.Data.NHibernate;
using Configuration = NHibernate.Cfg.Configuration;
using Environment = NHibernate.Cfg.Environment;
using Abeced.Data;

namespace Abeced.Data
{
    public partial class AbecedDataContext : NHibernateDataContext
    {
        #region Session Implementation

        private static object _sessionFactoryLock = new object();

        private static ISessionFactory _sessionFactory = null;

        private ISessionFactory SessionFactory
        {
            get
            {
                lock (_sessionFactoryLock)
                    if (_sessionFactory == null)
                        _sessionFactory = CreateSessionFactory("abeced_db",
                            "Abeced.Data",
                            "NHibernate.Dialect.PostgreSQLDialect",
                            "NHibernate.Driver.NpgsqlDriver");

                return _sessionFactory;
            }
        }

        protected override ISession CreateSession()
        {
            return SessionFactory.OpenSession();
        }
        
        protected override IStatelessSession CreateStatelessSession()
        {
            return SessionFactory.OpenStatelessSession();
        }
        
        #endregion
        
        #region Tables
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.AllCard> _allCard;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.AllCard> AllCard
        {
            get
            {
                if (_allCard == null)
                    _allCard = new Table<Abeced.Data.AllCard>(this);
                return _allCard;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.CardRevision> _cardRevision;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.CardRevision> CardRevision
        {
            get
            {
                if (_cardRevision == null)
                    _cardRevision = new Table<Abeced.Data.CardRevision>(this);
                return _cardRevision;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.Cardsession> _cardsession;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.Cardsession> Cardsession
        {
            get
            {
                if (_cardsession == null)
                    _cardsession = new Table<Abeced.Data.Cardsession>(this);
                return _cardsession;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.Flashcard> _flashcard;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.Flashcard> Flashcard
        {
            get
            {
                if (_flashcard == null)
                    _flashcard = new Table<Abeced.Data.Flashcard>(this);
                return _flashcard;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.Invitation> _invitation;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.Invitation> Invitation
        {
            get
            {
                if (_invitation == null)
                    _invitation = new Table<Abeced.Data.Invitation>(this);
                return _invitation;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.LookupAgegroup> _lookupAgegroup;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.LookupAgegroup> LookupAgegroup
        {
            get
            {
                if (_lookupAgegroup == null)
                    _lookupAgegroup = new Table<Abeced.Data.LookupAgegroup>(this);
                return _lookupAgegroup;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.LookupCategory> _lookupCategory;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.LookupCategory> LookupCategory
        {
            get
            {
                if (_lookupCategory == null)
                    _lookupCategory = new Table<Abeced.Data.LookupCategory>(this);
                return _lookupCategory;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.LookupEducLevel> _lookupEducLevel;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.LookupEducLevel> LookupEducLevel
        {
            get
            {
                if (_lookupEducLevel == null)
                    _lookupEducLevel = new Table<Abeced.Data.LookupEducLevel>(this);
                return _lookupEducLevel;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.LookupRevisetime> _lookupRevisetime;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.LookupRevisetime> LookupRevisetime
        {
            get
            {
                if (_lookupRevisetime == null)
                    _lookupRevisetime = new Table<Abeced.Data.LookupRevisetime>(this);
                return _lookupRevisetime;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.LookupSubcategory> _lookupSubcategory;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.LookupSubcategory> LookupSubcategory
        {
            get
            {
                if (_lookupSubcategory == null)
                    _lookupSubcategory = new Table<Abeced.Data.LookupSubcategory>(this);
                return _lookupSubcategory;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.Messageofday> _messageofday;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.Messageofday> Messageofday
        {
            get
            {
                if (_messageofday == null)
                    _messageofday = new Table<Abeced.Data.Messageofday>(this);
                return _messageofday;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.PasswordReset> _passwordReset;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.PasswordReset> PasswordReset
        {
            get
            {
                if (_passwordReset == null)
                    _passwordReset = new Table<Abeced.Data.PasswordReset>(this);
                return _passwordReset;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.Person> _person;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.Person> Person
        {
            get
            {
                if (_person == null)
                    _person = new Table<Abeced.Data.Person>(this);
                return _person;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Abeced.Data.QuizScore> _quizScore;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Abeced.Data.QuizScore> QuizScore
        {
            get
            {
                if (_quizScore == null)
                    _quizScore = new Table<Abeced.Data.QuizScore>(this);
                return _quizScore;
            }
        }
        
        #endregion
        
        #region Views
        
        #endregion
        
        #region Functions
        
        #endregion
    }
}
